#!/usr/bin/env bash
# SPDX-License-Identifier: BUSL-1.1
# SPDX-FileCopyrightText: 2026 Callandor GmbH and contributors
#
# Phase-2 Sprint-9 Tag-5 — Disposable Wakir-Pilot Acceptance-Gate VM
#                          provisioner (vm-up).
#
# Provider-agnostic entry point. Selects between `qemu` (default, self-
# contained KVM VM) and `proxmox` (clone from the canonical Pilot
# template). On success writes a state file to $STATE_DIR/vm.env that
# subsequent harness scripts (vm-bringup-run.sh, acceptance-gate.sh,
# vm-down.sh) source to learn the VM's IP, SSH key path, and provider-
# specific destroy handle.
#
# Sandbox-Grenze (ADR-0051): MUST NOT run in claude-dev. Operator-Hand
# only.

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

: "${WAKIR_E2E_VM_PROVIDER:=qemu}"
: "${WAKIR_E2E_STATE_DIR:=/var/lib/wakir-e2e}"
: "${WAKIR_E2E_VM_NAME:=wakir-pilot-e2e-$(date -u +%Y%m%dT%H%M%SZ)}"
: "${WAKIR_E2E_VM_MEMORY_MB:=4096}"
: "${WAKIR_E2E_VM_VCPUS:=4}"
: "${WAKIR_E2E_VM_DISK_GB:=32}"

# qemu provider config
: "${WAKIR_E2E_FCOS_QCOW2_URL:=https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/40.20240825.3.0/x86_64/fedora-coreos-40.20240825.3.0-qemu.x86_64.qcow2.xz}"
: "${WAKIR_E2E_FCOS_QCOW2_SHA256:=DIGEST_PENDING_OPERATOR_REVIEW}"
: "${WAKIR_E2E_FCOS_CACHE_DIR:=/var/cache/wakir-e2e/fcos}"

# proxmox provider config
: "${WAKIR_E2E_PROXMOX_TEMPLATE_VMID:=900}"
: "${WAKIR_E2E_PROXMOX_CLONE_VMID:=}"
: "${WAKIR_E2E_PROXMOX_STORAGE:=local-lvm}"
: "${WAKIR_E2E_PROXMOX_BRIDGE:=vmbr0}"

# Shared
: "${WAKIR_E2E_SSH_KEY:=$HOME/.ssh/wakir-e2e-disposable}"
: "${WAKIR_E2E_SSH_READY_TIMEOUT_S:=300}"

STATE_DIR="$WAKIR_E2E_STATE_DIR"
STATE_FILE="$STATE_DIR/vm.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log()  { echo "[vm-up] $*" >&2; }
die()  { echo "[vm-up] ERROR: $*" >&2; exit 1; }
ok()   { echo "[vm-up] OK: $*" >&2; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

ensure_ssh_key() {
  if [[ ! -f "$WAKIR_E2E_SSH_KEY" ]]; then
    log "generating disposable ssh key at $WAKIR_E2E_SSH_KEY"
    mkdir -p "$(dirname "$WAKIR_E2E_SSH_KEY")"
    ssh-keygen -t ed25519 -N '' -C "wakir-e2e-disposable" \
      -f "$WAKIR_E2E_SSH_KEY" >/dev/null
  fi
  PUBKEY=$(cat "${WAKIR_E2E_SSH_KEY}.pub")
}

render_ignition() {
  local out="$1"
  local tmpl_dir
  tmpl_dir="$(dirname "$(readlink -f "$0")")"
  local tmpl="$tmpl_dir/ignition.bu.tmpl"
  [[ -f "$tmpl" ]] || die "missing template: $tmpl"
  local bu="$STATE_DIR/ignition.bu"
  sed \
    -e "s|__SSH_PUBKEY__|${PUBKEY}|g" \
    -e "s|__HOSTNAME__|${WAKIR_E2E_VM_NAME}|g" \
    "$tmpl" > "$bu"
  require_cmd butane
  butane --pretty --strict "$bu" > "$out"
  ok "rendered ignition config to $out"
}

wait_for_ssh() {
  local ip="$1"
  local deadline=$(( $(date +%s) + WAKIR_E2E_SSH_READY_TIMEOUT_S ))
  log "waiting for ssh:22 on $ip (timeout ${WAKIR_E2E_SSH_READY_TIMEOUT_S}s)"
  while (( $(date +%s) < deadline )); do
    if ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=5 \
        -o BatchMode=yes \
        -i "$WAKIR_E2E_SSH_KEY" \
        "core@$ip" \
        true 2>/dev/null; then
      ok "ssh ready on $ip"
      return 0
    fi
    sleep 5
  done
  die "ssh on $ip did not come up within ${WAKIR_E2E_SSH_READY_TIMEOUT_S}s"
}

write_state() {
  cat > "$STATE_FILE" <<EOF
# Generated by vm-up.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
WAKIR_E2E_VM_NAME="$WAKIR_E2E_VM_NAME"
WAKIR_E2E_VM_PROVIDER="$WAKIR_E2E_VM_PROVIDER"
WAKIR_E2E_VM_IP="$VM_IP"
WAKIR_E2E_SSH_KEY="$WAKIR_E2E_SSH_KEY"
WAKIR_E2E_DESTROY_HANDLE="$DESTROY_HANDLE"
WAKIR_E2E_STATE_DIR="$STATE_DIR"
EOF
  ok "state written: $STATE_FILE"
}

# ---------------------------------------------------------------------------
# qemu provider
# ---------------------------------------------------------------------------

provision_qemu() {
  require_cmd qemu-system-x86_64
  require_cmd butane
  require_cmd xz
  require_cmd sha256sum

  mkdir -p "$WAKIR_E2E_FCOS_CACHE_DIR"
  local xz_file="$WAKIR_E2E_FCOS_CACHE_DIR/$(basename "$WAKIR_E2E_FCOS_QCOW2_URL")"
  local qcow2_file="${xz_file%.xz}"

  if [[ ! -f "$qcow2_file" ]]; then
    log "downloading Fedora-CoreOS qcow2"
    curl -L -o "$xz_file" "$WAKIR_E2E_FCOS_QCOW2_URL"
    if [[ "$WAKIR_E2E_FCOS_QCOW2_SHA256" != "DIGEST_PENDING_OPERATOR_REVIEW" ]]; then
      local got
      got=$(sha256sum "$xz_file" | awk '{print $1}')
      [[ "$got" == "$WAKIR_E2E_FCOS_QCOW2_SHA256" ]] || die \
        "FCOS qcow2.xz sha256 mismatch: got $got, expected $WAKIR_E2E_FCOS_QCOW2_SHA256"
    else
      log "WARNING: WAKIR_E2E_FCOS_QCOW2_SHA256 is the pending-review placeholder. Operator-Hand must pin a real digest before the run is evidence-grade."
    fi
    xz -d "$xz_file"
  fi
  [[ -f "$qcow2_file" ]] || die "qcow2 not present after extract: $qcow2_file"

  # Make a per-run COW overlay so the cached qcow2 is not mutated.
  local disk="$STATE_DIR/$WAKIR_E2E_VM_NAME.qcow2"
  qemu-img create -f qcow2 -F qcow2 -b "$qcow2_file" "$disk" \
    "${WAKIR_E2E_VM_DISK_GB}G"

  local ign="$STATE_DIR/$WAKIR_E2E_VM_NAME.ign"
  render_ignition "$ign"

  # Pick a free TCP port for guest:22 forward.
  local fwd_port
  fwd_port=$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1])')

  local pidfile="$STATE_DIR/$WAKIR_E2E_VM_NAME.pid"
  local logfile="$STATE_DIR/$WAKIR_E2E_VM_NAME.qemu.log"

  log "starting qemu (memory=${WAKIR_E2E_VM_MEMORY_MB}MB vcpus=${WAKIR_E2E_VM_VCPUS} ssh-fwd=127.0.0.1:${fwd_port})"
  qemu-system-x86_64 \
    -name "$WAKIR_E2E_VM_NAME" \
    -m "$WAKIR_E2E_VM_MEMORY_MB" \
    -cpu host \
    -smp "$WAKIR_E2E_VM_VCPUS" \
    -enable-kvm \
    -nographic \
    -daemonize \
    -pidfile "$pidfile" \
    -serial "file:$logfile" \
    -drive "if=virtio,file=$disk,format=qcow2" \
    -fw_cfg "name=opt/com.coreos/config,file=$ign" \
    -netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${fwd_port}-:22" \
    -device "virtio-net-pci,netdev=net0"

  VM_IP="127.0.0.1"
  SSH_EXTRA_ARGS=("-p" "$fwd_port")
  DESTROY_HANDLE="qemu:$pidfile:$disk:$ign"

  # State must include the SSH port for vm-bringup-run.sh
  cat >> "$STATE_FILE.partial" <<EOF || true
WAKIR_E2E_SSH_PORT="$fwd_port"
EOF

  wait_for_ssh_via_port "$VM_IP" "$fwd_port"
}

wait_for_ssh_via_port() {
  local ip="$1" port="$2"
  local deadline=$(( $(date +%s) + WAKIR_E2E_SSH_READY_TIMEOUT_S ))
  log "waiting for ssh:$port on $ip (timeout ${WAKIR_E2E_SSH_READY_TIMEOUT_S}s)"
  while (( $(date +%s) < deadline )); do
    if ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=5 \
        -o BatchMode=yes \
        -p "$port" \
        -i "$WAKIR_E2E_SSH_KEY" \
        "core@$ip" \
        true 2>/dev/null; then
      ok "ssh ready on $ip:$port"
      return 0
    fi
    sleep 5
  done
  die "ssh on $ip:$port did not come up within ${WAKIR_E2E_SSH_READY_TIMEOUT_S}s"
}

# ---------------------------------------------------------------------------
# proxmox provider
# ---------------------------------------------------------------------------

provision_proxmox() {
  require_cmd qm
  [[ -n "$WAKIR_E2E_PROXMOX_TEMPLATE_VMID" ]] || die "WAKIR_E2E_PROXMOX_TEMPLATE_VMID required"
  local clone_id="${WAKIR_E2E_PROXMOX_CLONE_VMID:-$(( WAKIR_E2E_PROXMOX_TEMPLATE_VMID + RANDOM % 1000 + 1 ))}"

  log "cloning template VMID $WAKIR_E2E_PROXMOX_TEMPLATE_VMID -> $clone_id"
  qm clone "$WAKIR_E2E_PROXMOX_TEMPLATE_VMID" "$clone_id" \
    --name "$WAKIR_E2E_VM_NAME" \
    --storage "$WAKIR_E2E_PROXMOX_STORAGE" \
    --full 1
  qm start "$clone_id"

  log "waiting for guest-agent on $clone_id to publish IP"
  local deadline=$(( $(date +%s) + WAKIR_E2E_SSH_READY_TIMEOUT_S ))
  while (( $(date +%s) < deadline )); do
    VM_IP=$(qm guest cmd "$clone_id" network-get-interfaces 2>/dev/null \
      | python3 -c 'import json,sys
data=json.load(sys.stdin)
for i in data:
  if i.get("name") in ("eth0","ens18","ens3"):
    for a in i.get("ip-addresses", []):
      if a.get("ip-address-type") == "ipv4" and not a["ip-address"].startswith("127."):
        print(a["ip-address"]); sys.exit(0)
sys.exit(1)' 2>/dev/null || true)
    if [[ -n "$VM_IP" ]]; then
      ok "VM IP: $VM_IP"
      break
    fi
    sleep 5
  done
  [[ -n "$VM_IP" ]] || die "guest-agent did not return an IPv4 within timeout"

  DESTROY_HANDLE="proxmox:$clone_id"
  wait_for_ssh "$VM_IP"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

main() {
  mkdir -p "$STATE_DIR"
  : > "$STATE_FILE.partial"
  ensure_ssh_key

  log "provider=$WAKIR_E2E_VM_PROVIDER vm=$WAKIR_E2E_VM_NAME"

  case "$WAKIR_E2E_VM_PROVIDER" in
    qemu)
      provision_qemu
      ;;
    proxmox)
      provision_proxmox
      ;;
    *)
      die "unknown WAKIR_E2E_VM_PROVIDER: $WAKIR_E2E_VM_PROVIDER (expected: qemu|proxmox)"
      ;;
  esac

  write_state
  if [[ -s "$STATE_FILE.partial" ]]; then
    cat "$STATE_FILE.partial" >> "$STATE_FILE"
    rm -f "$STATE_FILE.partial"
  fi
  ok "VM up; state at $STATE_FILE"
}

main "$@"
