#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Callandor GmbH and contributors
"""backend-decision-observability — Tag-22 Backend-Decision-Aggregator (SRE).

Background
----------

Phase-3b production-default switches (Tag-17 through Tag-21) wire five
``BackendDecision`` emit points in
:mod:`wirelang.persona_engine.rust_backend_switch`, one per
component:

  * ``recovery``      — Tag-17 (PR #168)
  * ``state_backing`` — Tag-17 (PR #168, twin emit-point)
  * ``fsm``           — Tag-18 (PR #169)
  * ``v907_verify``   — Tag-19 (PR #171)
  * ``bridge_diff``   — Tag-20 (PR #175)

Each engine boot emits one ``BackendDecision`` record per component
through :func:`log_backend_decision` into the engine's log_sink. The
on-disk schema (see ``log_backend_decision`` in
``wirelang/persona_engine/rust_backend_switch.py``) is::

    {
        "level": "INFO",
        "msg": "backend-decision",
        "domain": "recovery|state_backing|fsm|v907_verify|bridge_diff",
        "requested_backend": "<env-normalised>",
        "chosen_backend": "rust|python|rust_inmemory|rust_natskv|...",
        "resolution_latency_us": <int>,
        "fallback_reason": "binary_missing|binary_not_executable|explicit_python|null",
        "bin_path": "<path>|null"
    }

Until this Tag-22 aggregator lands, there is no centralized
observability over these records: an operator who wants to know
"what share of Phase-3b boots are still falling back to Python on
the v907_verify component" has to grep the JSONL by hand. This
aggregator is the SRE-side substrate that turns the per-boot
records into a five-component dashboard.

It is the **per-component-backend parallel** to the existing
per-routing-mode aggregator (Noa Tag-16, PR #161) and per-model
cost aggregator (Noa PR #110). Together those three views answer
"which model did the router pick" (Tag-16), "what did each model
cost" (PR #110), and now "which language backend did each engine
component boot under" (Tag-22).

The companion Grafana dashboard is
``dashboards/persona-engine-backend-decisions.json``.

Schema alignment
----------------

The emit-point uses the field name ``domain`` for historical reasons
(it predates the formal Phase-3b naming). The aggregator and
dashboard surface this as ``component`` — operator-facing copy uses
"component" consistently with the Phase-3b ADRs (ADR-0061 et seq).
The JSONL field name itself is **not** renamed: every consumer of
this aggregator reads the JSONL through this module, and the
emit-point's existing audit-trail must remain byte-stable for
verifier replay. The mapping is purely a metric-label rename.

The aggregator also tolerates engine log_sink streams that
interleave ``backend-decision`` records with other structured
``msg``-tagged records (e.g. observability events, error frames).
Only records whose ``msg`` field equals ``"backend-decision"`` are
aggregated. Records without a ``msg`` field are accepted under the
liberal-reader principle — fixtures generated by tests that emit
the record directly (without an engine wrapper) lack the ``msg``
envelope but still carry the substantive fields.

Sliding-window semantics
------------------------

BackendDecision JSONL grows one record per component per engine
boot. At Wakir-internal boot cadence (≤ a few dozen boots per
hour) the file remains modest, but the aggregator still applies a
trailing-window discipline (parity with
``routing-decision-observability.py``) so the gauges reflect the
recent operational reality rather than the historical long-tail.

Window size is operator-tunable via ``WAKIR_BACKEND_DECISION_OBS_WINDOW``
(default 500 — half the routing-decisions default since
per-boot-cardinality is one record-per-component vs.
per-decision-cardinality of one-per-request).

Aggregations
------------

The aggregator returns a single envelope dict with these top-level
keys:

  - ``sample_size``: number of decisions aggregated (0..N).
  - ``window_size``: configured N.
  - ``count_per_component_backend``: dict
    ``{component -> {backend -> int}}`` giving the python-vs-rust
    split per component. ``backend`` is the JSONL ``chosen_backend``
    value, lower-cased; null/missing maps to the sentinel
    ``backend_unknown``. Unknown components map to
    ``component_unknown``.
  - ``count_per_component``: dict ``{component -> int}`` total
    decisions per component (sum of the inner dict). Useful for
    quick parity-check "did all 5 components emit this boot".
  - ``latency_per_component``: dict
    ``{component -> {avg, p50, p95, p99, count}}`` with
    **nearest-rank** percentile semantics over
    ``resolution_latency_us`` (microseconds). ``avg`` is float; the
    quantile keys are integers; ``count`` is the per-component
    sample size after dropping records with malformed/missing
    latency.
  - ``fallback_counts_per_component``: dict ``{component -> int}``
    of decisions whose ``fallback_reason`` is a non-null string.
    A fallback signals the operator-requested backend was not
    available and the switch coerced down to Python.
  - ``fallback_rate_per_component``: dict ``{component -> float}``
    of ``fallbacks / decisions`` in [0, 1]; 0.0 when the
    component has zero observations (an explicit zero-traffic
    rule, not silent-1.0).
  - ``aggregated_fallback_rate``: float of total-fallbacks /
    total-decisions across all components; 0.0 when sample is
    empty.

Outputs
-------

Two output formats:

  - ``--format=json``: the envelope above as a single JSON object.
    Operator-facing; default.
  - ``--format=prometheus``: Prometheus exposition format for the
    node-exporter textfile collector.

The two formats expose the same numbers. The Grafana dashboard
``dashboards/persona-engine-backend-decisions.json`` consumes the
Prometheus gauges.

Run mode
--------

Stdlib-only. Driven by a 5-minute systemd-user-timer cadence
inside the ``claude-dev`` toolbox container — the same substrate
Kai already runs for the cost, cache, and routing aggregators.

Exit codes
----------

* ``0`` — aggregator ran cleanly.
* ``1`` — JSONL path missing or unreadable.
* ``2`` — textfile output directory not writable (Prometheus mode).

License: Apache-2.0 (parity with sibling aggregators).
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import tempfile
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional


# ---------------------------------------------------------------------------
# ENV contract + defaults
# ---------------------------------------------------------------------------

#: Env-var the persona-engine writes its log_sink to. The
#: BackendDecision records flow through that sink alongside other
#: structured events. The aggregator filters by ``msg`` field, so
#: pointing this at the engine's main log_sink path is correct.
#: When the deployment splits BackendDecision into a dedicated
#: sink (future hardening), the same env-var continues to work.
WAKIR_BACKEND_DECISION_JSONL_ENV = "WAKIR_BACKEND_DECISION_JSONL"

#: Env-var the aggregator reads to size the sliding window.
WAKIR_BACKEND_DECISION_OBS_WINDOW_ENV = "WAKIR_BACKEND_DECISION_OBS_WINDOW"

#: Default sliding-window size when the env-var is unset or
#: non-positive. Half the routing-decisions default (1000) since
#: BackendDecisions are emitted at boot-cadence, not per-request.
DEFAULT_WINDOW_SIZE = 500

#: Default textfile-collector output path (parity with sibling
#: aggregators).
DEFAULT_TEXTFILE_OUTPUT = (
    "/var/lib/node_exporter/textfile_collector/backend_decisions.prom"
)

#: Components per ADR-0061 et seq (Phase-3b switches). Mirrors the
#: ``domain=...`` values emitted by
#: :mod:`wirelang.persona_engine.rust_backend_switch`. Kept locally
#: so the aggregator stays stdlib-only.
COMPONENT_RECOVERY = "recovery"
COMPONENT_STATE_BACKING = "state_backing"
COMPONENT_FSM = "fsm"
COMPONENT_V907_VERIFY = "v907_verify"
COMPONENT_BRIDGE_DIFF = "bridge_diff"

KNOWN_COMPONENTS = (
    COMPONENT_RECOVERY,
    COMPONENT_STATE_BACKING,
    COMPONENT_FSM,
    COMPONENT_V907_VERIFY,
    COMPONENT_BRIDGE_DIFF,
)

#: Bucket key for records whose ``domain`` field is missing or not
#: in :data:`KNOWN_COMPONENTS`. Drift surfaces in the unknown gauge.
COMPONENT_UNKNOWN_BUCKET = "component_unknown"

#: Bucket key for records whose ``chosen_backend`` field is null /
#: missing. We do not silently drop these.
BACKEND_UNKNOWN_BUCKET = "backend_unknown"

#: Wire-string the engine emits to identify a BackendDecision record
#: in a mixed log_sink stream. Anything else is skipped during
#: aggregation; records without a ``msg`` field are accepted (liberal
#: reader for direct-fixture-emit test inputs).
BACKEND_DECISION_MSG = "backend-decision"


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class JsonlReadError(RuntimeError):
    """Raised when the backend-decision JSONL is missing or unreadable."""


# ---------------------------------------------------------------------------
# JSONL parsing + sliding-window selection
# ---------------------------------------------------------------------------


def _is_backend_decision_record(obj: Any) -> bool:
    """Return True when ``obj`` is a dict that looks like a backend-decision.

    Acceptance criteria:
      - ``obj`` is a dict.
      - Either no ``msg`` field is present (liberal-reader: direct
        fixture-emit without engine envelope), or the ``msg`` field
        equals :data:`BACKEND_DECISION_MSG`.

    All other dicts (e.g. observability events, error frames in a
    mixed engine log_sink) are filtered out before aggregation.
    """
    if not isinstance(obj, dict):
        return False
    msg = obj.get("msg")
    if msg is None:
        # No msg envelope — accept (test fixtures often emit raw).
        return True
    return msg == BACKEND_DECISION_MSG


def read_decision_records(jsonl_path: Path) -> List[Dict[str, Any]]:
    """Parse the backend-decision JSONL into a list of dicts.

    Tolerates blank lines and malformed JSON (skips both). Returns
    an empty list when the file is empty; raises
    :class:`JsonlReadError` when the file is missing or unreadable.

    Records whose ``msg`` field is present and not equal to
    :data:`BACKEND_DECISION_MSG` are silently skipped — the engine
    log_sink is a shared stream and other event types must not
    contaminate the aggregator.
    """
    if not jsonl_path.is_file():
        raise JsonlReadError(
            f"backend-decision JSONL {jsonl_path} is not a regular file"
        )
    try:
        with jsonl_path.open("rb") as fh:
            data = fh.read()
    except OSError as exc:
        raise JsonlReadError(
            f"cannot read backend-decision JSONL {jsonl_path}: {exc}"
        ) from exc
    records: List[Dict[str, Any]] = []
    for raw in data.decode("utf-8", errors="replace").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if _is_backend_decision_record(obj):
            records.append(obj)
    return records


def select_window(
    records: List[Dict[str, Any]], window_size: int
) -> List[Dict[str, Any]]:
    """Return the trailing ``window_size`` records (or all if shorter).

    A non-positive ``window_size`` is normalised to
    :data:`DEFAULT_WINDOW_SIZE` so a misconfigured env-var cannot
    silently disable windowing.
    """
    if window_size <= 0:
        window_size = DEFAULT_WINDOW_SIZE
    if len(records) <= window_size:
        return list(records)
    return records[-window_size:]


def read_window_size_from_env(env: Mapping[str, str]) -> int:
    """Return the configured window size from the env-map.

    Invalid values (non-int, <= 0) fall back to
    :data:`DEFAULT_WINDOW_SIZE`. The aggregator never raises on a
    bad env-var — operator misconfiguration must not break the
    metrics pipeline.
    """
    raw = env.get(WAKIR_BACKEND_DECISION_OBS_WINDOW_ENV, "").strip()
    if not raw:
        return DEFAULT_WINDOW_SIZE
    try:
        value = int(raw)
    except ValueError:
        return DEFAULT_WINDOW_SIZE
    if value <= 0:
        return DEFAULT_WINDOW_SIZE
    return value


# ---------------------------------------------------------------------------
# Field extraction helpers
# ---------------------------------------------------------------------------


def _safe_component(value: Any) -> str:
    """Coerce ``domain`` field to a known component or the unknown sentinel."""
    if isinstance(value, str) and value in KNOWN_COMPONENTS:
        return value
    return COMPONENT_UNKNOWN_BUCKET


def _safe_backend(value: Any) -> str:
    """Coerce ``chosen_backend`` to a non-empty str or the unknown sentinel."""
    if isinstance(value, str) and value:
        return value
    return BACKEND_UNKNOWN_BUCKET


def _safe_int_latency(value: Any) -> Optional[int]:
    """Return a non-negative int latency or ``None`` on bad input.

    Tolerates int and float (truncates). Rejects negatives, NaN,
    Inf, bool, and non-numeric types. Mirrors the defensive posture
    of ``routing-decision-observability.py``.
    """
    if isinstance(value, bool):
        # bool is an int subclass; we do not want True == 1us.
        return None
    if isinstance(value, int):
        return value if value >= 0 else None
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        ival = int(value)
        return ival if ival >= 0 else None
    return None


def _is_fallback(value: Any) -> bool:
    """Return True when ``fallback_reason`` indicates a real fallback.

    A non-null non-empty string is a fallback. ``None``, missing,
    or empty string is not. The substrate writes ``null`` (JSON) for
    the no-fallback case; we treat both ``None`` and empty string
    as equivalent for resilience to fixture drift.
    """
    if value is None:
        return False
    if isinstance(value, str) and value:
        return True
    return False


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------


def _nearest_rank_percentile(
    sorted_values: List[int], pct: float
) -> int:
    """Compute a nearest-rank percentile from a sorted ``int`` list.

    Returns 0 for an empty list. Pct is in [0, 100]. Nearest-rank
    (NIST) is preferred over linear interpolation here because the
    dashboard should display a *real measured latency*, not an
    interpolated phantom that no boot actually exhibited.
    """
    n = len(sorted_values)
    if n == 0:
        return 0
    pct = max(0.0, min(100.0, pct))
    rank = max(1, math.ceil((pct / 100.0) * n))
    rank = min(rank, n)
    return sorted_values[rank - 1]


def aggregate_decisions(
    records: Iterable[Mapping[str, Any]], *, window_size: int
) -> Dict[str, Any]:
    """Aggregate a sequence of BackendDecision records into the envelope.

    See module docstring for the envelope schema.
    """
    records_list = list(records)
    sample = select_window(records_list, window_size)

    count_per_component_backend: Dict[str, Dict[str, int]] = {}
    count_per_component: Dict[str, int] = {}
    latency_by_component: Dict[str, List[int]] = {}
    fallback_counts: Dict[str, int] = {}

    for rec in sample:
        component = _safe_component(rec.get("domain"))
        backend = _safe_backend(rec.get("chosen_backend"))

        per_backend = count_per_component_backend.setdefault(component, {})
        per_backend[backend] = per_backend.get(backend, 0) + 1
        count_per_component[component] = (
            count_per_component.get(component, 0) + 1
        )

        latency = _safe_int_latency(rec.get("resolution_latency_us"))
        if latency is not None:
            latency_by_component.setdefault(component, []).append(latency)

        if _is_fallback(rec.get("fallback_reason")):
            fallback_counts[component] = fallback_counts.get(component, 0) + 1

    latency_per_component: Dict[str, Dict[str, Any]] = {}
    for component, vals in latency_by_component.items():
        vals_sorted = sorted(vals)
        n = len(vals_sorted)
        avg = sum(vals_sorted) / n if n > 0 else 0.0
        latency_per_component[component] = {
            "avg": avg,
            "p50": _nearest_rank_percentile(vals_sorted, 50.0),
            "p95": _nearest_rank_percentile(vals_sorted, 95.0),
            "p99": _nearest_rank_percentile(vals_sorted, 99.0),
            "count": n,
        }

    # Fallback-rate per component. Components with zero observations
    # do not appear in count_per_component, hence the rate dict is
    # keyed by the same set. We intentionally do not pre-seed all
    # KNOWN_COMPONENTS with 0.0: the absence of a component-key in
    # the rate dict means "no observations", which the dashboard
    # renders distinctly from "0% fallback".
    fallback_rate_per_component: Dict[str, float] = {}
    for component, total in count_per_component.items():
        fallbacks = fallback_counts.get(component, 0)
        if total > 0:
            fallback_rate_per_component[component] = fallbacks / total
        else:
            fallback_rate_per_component[component] = 0.0

    total_decisions = sum(count_per_component.values())
    total_fallbacks = sum(fallback_counts.values())
    if total_decisions > 0:
        aggregated_fallback_rate = total_fallbacks / total_decisions
    else:
        aggregated_fallback_rate = 0.0

    return {
        "sample_size": len(sample),
        "window_size": window_size,
        "count_per_component_backend": count_per_component_backend,
        "count_per_component": count_per_component,
        "latency_per_component": latency_per_component,
        "fallback_counts_per_component": fallback_counts,
        "fallback_rate_per_component": fallback_rate_per_component,
        "aggregated_fallback_rate": aggregated_fallback_rate,
    }


# ---------------------------------------------------------------------------
# Prometheus textfile rendering
# ---------------------------------------------------------------------------


def render_prometheus(
    envelope: Mapping[str, Any], *, scrape_ts_utc: Optional[int] = None
) -> str:
    """Render the envelope as Prometheus exposition text.

    Metric schema (all gauges)::

        persona_engine_backend_decisions_sample_size
        persona_engine_backend_decisions_window_size
        persona_engine_backend_decisions_per_component_backend{component="...",backend="..."}
        persona_engine_backend_decisions_per_component{component="..."}
        persona_engine_backend_decision_latency_us{component="...",quantile="0.5|0.95|0.99"}
        persona_engine_backend_decision_latency_us_avg{component="..."}
        persona_engine_backend_decision_count_per_component{component="..."}
        persona_engine_backend_decision_fallbacks_total{component="..."}
        persona_engine_backend_decision_fallback_rate{component="..."}
        persona_engine_backend_decision_fallback_rate_aggregated
        persona_engine_backend_decisions_scrape_timestamp_seconds
    """
    if scrape_ts_utc is None:
        scrape_ts_utc = int(time.time())
    lines: List[str] = []

    def _emit_help(name: str, help_text: str, mtype: str = "gauge") -> None:
        lines.append(f"# HELP {name} {help_text}\n")
        lines.append(f"# TYPE {name} {mtype}\n")

    _emit_help(
        "persona_engine_backend_decisions_sample_size",
        "Number of backend-decision records aggregated in the current window.",
    )
    lines.append(
        f"persona_engine_backend_decisions_sample_size {envelope['sample_size']}\n"
    )

    _emit_help(
        "persona_engine_backend_decisions_window_size",
        "Configured sliding-window size (WAKIR_BACKEND_DECISION_OBS_WINDOW).",
    )
    lines.append(
        f"persona_engine_backend_decisions_window_size {envelope['window_size']}\n"
    )

    _emit_help(
        "persona_engine_backend_decisions_per_component_backend",
        "Per (component, chosen-backend) count of decisions in the current window.",
    )
    for component in sorted(envelope["count_per_component_backend"].keys()):
        per_backend = envelope["count_per_component_backend"][component]
        for backend in sorted(per_backend.keys()):
            value = per_backend[backend]
            lines.append(
                'persona_engine_backend_decisions_per_component_backend'
                f'{{component="{_escape_label(component)}",'
                f'backend="{_escape_label(backend)}"}} {value}\n'
            )

    _emit_help(
        "persona_engine_backend_decisions_per_component",
        "Per-component total decision count in the current window.",
    )
    for component in sorted(envelope["count_per_component"].keys()):
        value = envelope["count_per_component"][component]
        lines.append(
            'persona_engine_backend_decisions_per_component'
            f'{{component="{_escape_label(component)}"}} {value}\n'
        )

    _emit_help(
        "persona_engine_backend_decision_latency_us",
        "Per-component nearest-rank decision-resolution-latency percentile (microseconds).",
    )
    for component in sorted(envelope["latency_per_component"].keys()):
        bucket = envelope["latency_per_component"][component]
        for q_label, q_key in (
            ("0.5", "p50"),
            ("0.95", "p95"),
            ("0.99", "p99"),
        ):
            lines.append(
                'persona_engine_backend_decision_latency_us'
                f'{{component="{_escape_label(component)}",'
                f'quantile="{q_label}"}} {bucket[q_key]}\n'
            )

    _emit_help(
        "persona_engine_backend_decision_latency_us_avg",
        "Per-component arithmetic-mean decision-resolution-latency (microseconds).",
    )
    for component in sorted(envelope["latency_per_component"].keys()):
        bucket = envelope["latency_per_component"][component]
        lines.append(
            'persona_engine_backend_decision_latency_us_avg'
            f'{{component="{_escape_label(component)}"}}'
            f" {_format_value(bucket['avg'])}\n"
        )

    _emit_help(
        "persona_engine_backend_decision_count_per_component",
        "Per-component sample-count contributing to the latency percentile "
        "(filtered to records with a valid latency).",
    )
    for component in sorted(envelope["latency_per_component"].keys()):
        bucket = envelope["latency_per_component"][component]
        lines.append(
            'persona_engine_backend_decision_count_per_component'
            f'{{component="{_escape_label(component)}"}} {bucket["count"]}\n'
        )

    _emit_help(
        "persona_engine_backend_decision_fallbacks_total",
        "Per-component count of decisions whose fallback_reason is non-null.",
    )
    for component in sorted(envelope["fallback_counts_per_component"].keys()):
        value = envelope["fallback_counts_per_component"][component]
        lines.append(
            'persona_engine_backend_decision_fallbacks_total'
            f'{{component="{_escape_label(component)}"}} {value}\n'
        )

    _emit_help(
        "persona_engine_backend_decision_fallback_rate",
        "Per-component share of decisions that fell back to Python (0..1).",
    )
    for component in sorted(envelope["fallback_rate_per_component"].keys()):
        value = envelope["fallback_rate_per_component"][component]
        lines.append(
            'persona_engine_backend_decision_fallback_rate'
            f'{{component="{_escape_label(component)}"}}'
            f" {_format_value(value)}\n"
        )

    _emit_help(
        "persona_engine_backend_decision_fallback_rate_aggregated",
        "Cross-component aggregated fallback-rate "
        "(total fallbacks / total decisions, 0..1).",
    )
    lines.append(
        "persona_engine_backend_decision_fallback_rate_aggregated "
        f"{_format_value(envelope['aggregated_fallback_rate'])}\n"
    )

    _emit_help(
        "persona_engine_backend_decisions_scrape_timestamp_seconds",
        "POSIX-epoch timestamp at which the backend-decision aggregator "
        "last wrote the textfile.",
    )
    lines.append(
        "persona_engine_backend_decisions_scrape_timestamp_seconds "
        f"{scrape_ts_utc}\n"
    )

    return "".join(lines)


def _escape_label(v: str) -> str:
    """Prometheus label-value escaping: backslash, double-quote, newline."""
    return v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_value(v: float) -> str:
    """Format a float for Prometheus exposition (parity with sibling aggregators)."""
    if isinstance(v, bool):
        v = int(v)
    if isinstance(v, int):
        return str(v)
    if float(v).is_integer():
        return str(int(v))
    return f"{v:.10f}".rstrip("0").rstrip(".")


# ---------------------------------------------------------------------------
# Atomic textfile write (parity with cache-hit-rate-aggregator)
# ---------------------------------------------------------------------------


def atomic_write(target: Path, payload: str) -> None:
    """Write ``payload`` to ``target`` atomically via os.replace."""
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=str(target.parent),
        prefix=target.name + ".",
        suffix=".tmp",
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(payload)
        tmp_path = Path(tmp.name)
    os.replace(tmp_path, target)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="backend-decision-observability",
        description=(
            "Aggregator for per-boot BackendDecision telemetry emitted by "
            "the Phase-3b production-default switches in "
            "wirelang.persona_engine.rust_backend_switch. Outputs JSON "
            "for operators or Prometheus exposition for the "
            "node-exporter textfile collector. Tag-22 SRE artefact."
        ),
    )
    p.add_argument(
        "--jsonl-path",
        type=Path,
        default=None,
        help=(
            "Path to the backend-decision JSONL (engine log_sink). "
            f"Falls back to ${WAKIR_BACKEND_DECISION_JSONL_ENV}."
        ),
    )
    p.add_argument(
        "--window-size",
        type=int,
        default=None,
        help=(
            "Sliding-window size (most recent N decisions). Falls back "
            f"to ${WAKIR_BACKEND_DECISION_OBS_WINDOW_ENV} then "
            f"{DEFAULT_WINDOW_SIZE}."
        ),
    )
    p.add_argument(
        "--format",
        choices=("json", "prometheus"),
        default="json",
        help="Output format: json (default, operator-facing) or prometheus.",
    )
    p.add_argument(
        "--textfile-output",
        type=Path,
        default=Path(DEFAULT_TEXTFILE_OUTPUT),
        help=(
            "Prometheus textfile-collector output path (only used when "
            f"--format=prometheus). Default: {DEFAULT_TEXTFILE_OUTPUT}"
        ),
    )
    p.add_argument(
        "--now",
        type=int,
        default=None,
        help=(
            "Override the 'now' POSIX-epoch timestamp for hermetic tests. "
            "Production runs leave this unset and use time.time()."
        ),
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "In --format=prometheus mode: render to stdout instead of "
            "writing the textfile. In --format=json mode: no-op."
        ),
    )
    return p


def resolve_jsonl_path(
    cli_value: Optional[Path], env: Mapping[str, str]
) -> Optional[Path]:
    if cli_value is not None:
        return cli_value
    env_value = env.get(WAKIR_BACKEND_DECISION_JSONL_ENV, "").strip()
    if env_value:
        return Path(env_value)
    return None


def resolve_window_size(
    cli_value: Optional[int], env: Mapping[str, str]
) -> int:
    if cli_value is not None:
        if cli_value <= 0:
            return DEFAULT_WINDOW_SIZE
        return cli_value
    return read_window_size_from_env(env)


def main(
    argv: Optional[List[str]] = None,
    *,
    env: Optional[Mapping[str, str]] = None,
) -> int:
    args = build_argparser().parse_args(argv)
    env_map: Mapping[str, str] = env if env is not None else os.environ

    jsonl_path = resolve_jsonl_path(args.jsonl_path, env_map)
    if jsonl_path is None:
        sys.stderr.write(
            "backend-decision-observability: no JSONL path configured "
            f"(set --jsonl-path or ${WAKIR_BACKEND_DECISION_JSONL_ENV}).\n"
        )
        return 1

    try:
        records = read_decision_records(jsonl_path)
    except JsonlReadError as exc:
        sys.stderr.write(f"backend-decision-observability: {exc}\n")
        return 1

    window_size = resolve_window_size(args.window_size, env_map)
    envelope = aggregate_decisions(records, window_size=window_size)

    if args.format == "json":
        sys.stdout.write(json.dumps(envelope, sort_keys=True, indent=2))
        sys.stdout.write("\n")
        return 0

    # Prometheus path.
    now = args.now if args.now is not None else int(time.time())
    payload = render_prometheus(envelope, scrape_ts_utc=now)
    if args.dry_run:
        sys.stdout.write(payload)
        return 0
    try:
        atomic_write(args.textfile_output, payload)
    except OSError as exc:
        sys.stderr.write(
            f"backend-decision-observability: cannot write textfile output: {exc}\n"
        )
        return 2
    return 0


__all__ = [
    "BACKEND_DECISION_MSG",
    "BACKEND_UNKNOWN_BUCKET",
    "COMPONENT_BRIDGE_DIFF",
    "COMPONENT_FSM",
    "COMPONENT_RECOVERY",
    "COMPONENT_STATE_BACKING",
    "COMPONENT_UNKNOWN_BUCKET",
    "COMPONENT_V907_VERIFY",
    "DEFAULT_TEXTFILE_OUTPUT",
    "DEFAULT_WINDOW_SIZE",
    "JsonlReadError",
    "KNOWN_COMPONENTS",
    "WAKIR_BACKEND_DECISION_JSONL_ENV",
    "WAKIR_BACKEND_DECISION_OBS_WINDOW_ENV",
    "aggregate_decisions",
    "atomic_write",
    "build_argparser",
    "main",
    "read_decision_records",
    "read_window_size_from_env",
    "render_prometheus",
    "resolve_jsonl_path",
    "resolve_window_size",
    "select_window",
]


if __name__ == "__main__":
    sys.exit(main())
